name: gh-actions-language-server
description: |
  Github Actions Language Server
homepage: https://github.com/lttb/gh-actions-language-server
licenses:
  - MIT
languages:
  - YAML
categories:
  - LSP
source:
  # renovate:versioning=loose
  id: pkg:npm/gh-actions-language-server@0.0.3
bin:
  gh-actions-language-server: npm:gh-actions-language-server
